"""Model comparison visualization — reads benchmark results and generates charts.

Generates:
    - Bar charts comparing AUC-ROC, F1, Score Ratio, Training Time
    - Overlaid ROC curves for all models
    - Precision / Recall / F1 grouped bar chart
    - Full ranking table printed to console

Usage:
    cd bin
    python -m model.compare

Requires: benchmark results in benchmark_results/results.json
          (generated by `python -m model.benchmark`)
"""

import json
import sys
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')  # non-interactive backend — works without display
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

RESULTS_DIR = Path('benchmark_results')


# ============================================================================
# DATA LOADING
# ============================================================================

def load_results() -> list[dict]:
    """Load benchmark results from JSON, filtering out failed models."""
    results_path = RESULTS_DIR / 'results.json'
    if not results_path.exists():
        print(f"Error: Results not found at {results_path}")
        print("Run 'python -m model.benchmark' first.")
        sys.exit(1)

    with open(results_path, 'r') as f:
        results = json.load(f)

    valid = [r for r in results if 'error' not in r]
    if not valid:
        print("No valid model results found.")
        sys.exit(1)

    return valid


# ============================================================================
# COLOUR PALETTE
# ============================================================================

def _get_colors(n: int) -> list:
    """Return a distinguishable colour palette of size *n*."""
    cmap = plt.cm.get_cmap('tab20' if n > 10 else 'tab10')
    return [cmap(i / max(n - 1, 1)) for i in range(n)]


# ============================================================================
# 1. BAR CHARTS — AUC-ROC, F1, Score Ratio, Training Time
# ============================================================================

def plot_metrics_comparison(results: list[dict]):
    """Horizontal bar charts for the three key quality metrics.

    Training time was dropped from this figure: it is a hardware/run-condition
    artefact that carries no information about detection quality.
    """
    fig, axes = plt.subplots(1, 3, figsize=(18, 7))

    # Sort by AUC-ROC
    results_sorted = sorted(results, key=lambda r: r.get('auc_roc', 0))
    names = [r['model_name'] for r in results_sorted]
    colors = _get_colors(len(names))

    def _bar(ax, values, xlabel, title, xlim=None, fmt='.3f', ref_line=None):
        bars = ax.barh(names, values, color=colors)
        ax.set_xlabel(xlabel)
        ax.set_title(title)
        if xlim:
            ax.set_xlim(xlim)
        if ref_line is not None:
            ax.axvline(x=ref_line, color='red', linestyle='--', alpha=0.5)
        span = ax.get_xlim()[1] - ax.get_xlim()[0]
        for bar, val in zip(bars, values):
            label = f'{val:{fmt}}'
            ax.text(val + span * 0.01, bar.get_y() + bar.get_height() / 2,
                    label, va='center', fontsize=9)

    # AUC-ROC
    _bar(axes[0],
         [r.get('auc_roc', 0) for r in results_sorted],
         'AUC-ROC', 'AUC-ROC (higher is better)',
         xlim=(0, 1.12), ref_line=0.5)

    # F1
    _bar(axes[1],
         [r.get('f1', 0) for r in results_sorted],
         'F1 Score', 'F1 Score at Optimal Threshold (higher is better)',
         xlim=(0, 1.12))

    # Score Ratio
    _bar(axes[2],
         [r.get('score_ratio', 0) for r in results_sorted],
         'Abnormal / Normal', 'Anomaly Score Ratio (higher is better)',
         fmt='.2f')

    # Only the leftmost panel keeps the model labels (shared ordering)
    for ax in axes[1:]:
        ax.set_yticklabels([])

    plt.tight_layout()
    save_path = RESULTS_DIR / 'comparison_bar_chart.png'
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.savefig(save_path.with_suffix('.pdf'), dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Bar chart saved to {save_path}")


# ============================================================================
# 2. ROC CURVES — all models overlaid
# ============================================================================

def plot_roc_curves(results: list[dict]):
    """Overlay ROC curves for every model on a single plot."""
    fig, ax = plt.subplots(figsize=(10, 8))
    colors = _get_colors(len(results))

    # Sort by AUC-ROC descending for legend ordering
    results_sorted = sorted(results, key=lambda r: r.get('auc_roc', 0), reverse=True)

    for i, r in enumerate(results_sorted):
        roc = r.get('roc_curve', {})
        fpr, tpr = roc.get('fpr', []), roc.get('tpr', [])
        if fpr and tpr:
            auc = r.get('auc_roc', 0)
            ax.plot(fpr, tpr, color=colors[i], linewidth=2,
                    label=f"{r['model_name']} (AUC={auc:.3f})")

    ax.plot([0, 1], [0, 1], 'k--', linewidth=1, alpha=0.5, label='Random (AUC=0.500)')
    ax.set_xlabel('False Positive Rate', fontsize=12)
    ax.set_ylabel('True Positive Rate', fontsize=12)
    ax.set_title('ROC Curves — All Models', fontsize=14, fontweight='bold')
    ax.legend(loc='lower right', fontsize=9)
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.02)
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    save_path = RESULTS_DIR / 'roc_curves.png'
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.savefig(save_path.with_suffix('.pdf'), dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  ROC curves saved to {save_path}")


# ============================================================================
# 3. PRECISION / RECALL / F1 grouped bar chart
# ============================================================================

def plot_precision_recall(results: list[dict]):
    """Grouped bar chart of Precision, Recall, and F1 for every model."""
    results_sorted = sorted(results, key=lambda r: r.get('f1', 0), reverse=True)
    names = [r['model_name'] for r in results_sorted]

    x = np.arange(len(names))
    width = 0.25

    precisions = [r.get('precision', 0) for r in results_sorted]
    recalls    = [r.get('recall', 0) for r in results_sorted]
    f1s        = [r.get('f1', 0) for r in results_sorted]

    fig, ax = plt.subplots(figsize=(15, 6))
    ax.bar(x - width, precisions, width, label='Precision', color='#2196F3')
    ax.bar(x,         recalls,    width, label='Recall',    color='#FF9800')
    ax.bar(x + width, f1s,        width, label='F1 Score',  color='#4CAF50')

    ax.set_ylabel('Score')
    ax.set_title('Precision, Recall & F1 — All Models', fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=30, ha='right')
    ax.legend()
    ax.set_ylim(0, 1.1)
    ax.grid(True, axis='y', alpha=0.3)

    plt.tight_layout()
    save_path = RESULTS_DIR / 'precision_recall.png'
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.savefig(save_path.with_suffix('.pdf'), dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Precision-Recall chart saved to {save_path}")


# ============================================================================
# 4. MAE COMPARISON (reconstruction-based models only)
# ============================================================================

def plot_mae_comparison(results: list[dict]):
    """Bar chart comparing MAE on normal vs abnormal for reconstruction models."""
    recon_models = [r for r in results
                    if r.get('mae_normal') is not None and r.get('mae_abnormal') is not None]
    if not recon_models:
        return

    recon_sorted = sorted(recon_models, key=lambda r: r.get('mae_ratio', 0), reverse=True)
    names = [r['model_name'] for r in recon_sorted]

    x = np.arange(len(names))
    width = 0.35

    mae_n = [r['mae_normal'] for r in recon_sorted]
    mae_a = [r['mae_abnormal'] for r in recon_sorted]

    fig, ax = plt.subplots(figsize=(14, 6))
    bars1 = ax.bar(x - width / 2, mae_n, width, label='MAE Normal', color='#66BB6A')
    bars2 = ax.bar(x + width / 2, mae_a, width, label='MAE Abnormal', color='#EF5350')

    ax.set_ylabel('Mean Absolute Error')
    ax.set_title('Reconstruction MAE — Normal vs Abnormal', fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=30, ha='right')
    ax.legend()
    ax.grid(True, axis='y', alpha=0.3)

    # Annotate MAE ratio
    for i, r in enumerate(recon_sorted):
        ratio = r.get('mae_ratio', 0)
        max_h = max(mae_n[i], mae_a[i])
        ax.text(i, max_h * 1.02, f'ratio={ratio:.2f}', ha='center', fontsize=9, fontweight='bold')

    plt.tight_layout()
    save_path = RESULTS_DIR / 'mae_comparison.png'
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.savefig(save_path.with_suffix('.pdf'), dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  MAE comparison saved to {save_path}")


# ============================================================================
# FULL RANKING TABLE (console)
# ============================================================================

def print_full_ranking(results: list[dict]):
    """Print comprehensive ranking table to stdout."""
    sorted_results = sorted(results, key=lambda r: r.get('auc_roc', 0), reverse=True)

    print("\n" + "=" * 110)
    print("FULL MODEL RANKING")
    print("=" * 110)

    header = (
        f"{'Rank':<5} {'Model':<22} {'Type':<12} {'AUC-ROC':<10} {'F1':<8} "
        f"{'Precision':<11} {'Recall':<9} {'MAE Ratio':<11} {'Score Ratio':<13} {'Time(s)':<8}"
    )
    print(header)
    print("-" * len(header))

    for i, r in enumerate(sorted_results, 1):
        m_type = 'Neural Net' if r['model_type'] == 'neural_network' else 'Classical'
        mae_r = f"{r['mae_ratio']:.4f}" if r.get('mae_ratio') is not None else "N/A"
        print(
            f"{i:<5} {r['model_name']:<22} {m_type:<12} "
            f"{r['auc_roc']:<10.4f} {r['f1']:<8.4f} "
            f"{r.get('precision', 0):<11.4f} {r.get('recall', 0):<9.4f} "
            f"{mae_r:<11} {r['score_ratio']:<13.4f} {r['train_time_s']:<8.1f}"
        )

    # ── Recommendations ────────────────────────────────────────────────
    print("\n" + "=" * 110)
    print("RECOMMENDATIONS")
    print("=" * 110)

    best_auc = sorted_results[0]
    best_f1 = max(sorted_results, key=lambda r: r.get('f1', 0))
    best_speed = min(sorted_results, key=lambda r: r.get('train_time_s', float('inf')))

    nn_results = [r for r in sorted_results if r['model_type'] == 'neural_network']
    cl_results = [r for r in sorted_results if r['model_type'] == 'classical_ml']

    print(f"\n  Best overall (AUC-ROC):     {best_auc['model_name']} ({best_auc['auc_roc']:.4f})")
    print(f"  Best classification (F1):   {best_f1['model_name']} ({best_f1['f1']:.4f})")
    print(f"  Fastest training:           {best_speed['model_name']} ({best_speed['train_time_s']:.1f}s)")

    if nn_results:
        best_nn = nn_results[0]
        print(f"  Best neural network:        {best_nn['model_name']} ({best_nn['auc_roc']:.4f})")
    if cl_results:
        best_cl = max(cl_results, key=lambda r: r.get('auc_roc', 0))
        print(f"  Best classical ML:          {best_cl['model_name']} ({best_cl['auc_roc']:.4f})")

    print("\n" + "=" * 110)


# ============================================================================
# LATEX TABLE EXPORT
# ============================================================================

def export_latex_table(results: list[dict]):
    """Export comparison table as LaTeX booktabs snippet."""
    sorted_results = sorted(results, key=lambda r: r.get('auc_roc', 0), reverse=True)

    lines = []
    lines.append(r'\begin{table}[H]')
    lines.append(r'    \centering')
    lines.append(r'    \caption{Comparativa de arquitecturas de detección de anomalías. '
                 r'AUC-ROC, F1, Precisión y Recall calculados con umbral de Youden. '
                 r'MAE Ratio = MAE\_anómalo / MAE\_normal. '
                 r'Los modelos de producción (en negrita) utilizan los pesos finales obtenidos mediante '
                 r'optimización bayesiana con Optuna en hardware CUDA; '
                 r'sus métricas constituyen las referencias de rendimiento del sistema desplegado.}')
    lines.append(r'    \label{tab:benchmark-comparison}')
    lines.append(r'    \begin{tabular}{lcccccc}')
    lines.append(r'    \toprule')
    lines.append(r'    Modelo & Tipo & AUC-ROC & F1 & Precisión & Recall & MAE Ratio \\')
    lines.append(r'    \midrule')

    for r in sorted_results:
        name = r['model_name']
        m_type = 'Red neuronal' if r['model_type'] == 'neural_network' else 'ML clásico'
        auc  = f"{r.get('auc_roc', 0):.4f}"
        f1   = f"{r.get('f1', 0):.4f}"
        prec = f"{r.get('precision', 0):.4f}"
        rec  = f"{r.get('recall', 0):.4f}"
        mae_r = f"{r['mae_ratio']:.4f}" if r.get('mae_ratio') is not None else '--'

        # Bold both production model rows
        _prod = {'VAE (Producción)', 'CVAE Nivel 1 (Producción)'}
        if name in _prod:
            row = (f'    \\textbf{{{name}}} & \\textbf{{{m_type}}} & '
                   f'\\textbf{{{auc}}} & \\textbf{{{f1}}} & '
                   f'\\textbf{{{prec}}} & \\textbf{{{rec}}} & '
                   f'\\textbf{{{mae_r}}} \\\\')
        else:
            row = f'    {name} & {m_type} & {auc} & {f1} & {prec} & {rec} & {mae_r} \\\\'
        lines.append(row)

    lines.append(r'    \bottomrule')
    lines.append(r'    \end{tabular}')
    lines.append(r'\end{table}')

    tex_content = '\n'.join(lines) + '\n'
    save_path = RESULTS_DIR / 'comparison_table.tex'
    save_path.write_text(tex_content, encoding='utf-8')
    print(f"  LaTeX table saved to {save_path}")


# ============================================================================
# ENTRY POINT
# ============================================================================

def main():
    import matplotlib
    matplotlib.rcParams.update({'font.size': 11})

    results = load_results()
    print(f"Loaded {len(results)} model results\n")

    # Generate all plots
    print("Generating comparison charts...")
    plot_metrics_comparison(results)
    plot_roc_curves(results)
    plot_precision_recall(results)
    plot_mae_comparison(results)

    # Console ranking
    print_full_ranking(results)

    export_latex_table(results)

    print(f"\nAll charts saved to {RESULTS_DIR}/")


if __name__ == '__main__':
    main()
